setwd("/home/bandana/Documents/HapGUI_package/final_apps/HapGUI")
dir <- getwd()
ip_dir <- "softwares"
options(shiny.maxRequestSize = 1000*1024^2)
source("ui.R")
source("server.R")

library(profvis)
library(shiny)
library(shinythemes)
library(shinyFiles)
library(fs)
library(htmltools)
library(mrMLM)
library(dplyr)
library(CMplot)
library(bestNormalize)
library(tidyr)
library(plyr)
library(tidyverse)
library(haplotypes)
library(agricolae)
library(ggplot2)
library(ggpubr)
library(ggridges)
library(plotly)
library(readxl)
library(RColorBrewer)
library(crayon)
library(stringr)
library(berryFunctions)
library(imager)
library(yhat)
library(corrplot)
library(augmentedRCBD)
library(lme4)
library(data.table)
library(ggfortify)
library(extrafont)
library(stats)
library(psych)
library(foreach)
library(doParallel)
library(qqman)
library(reshape2)

library(vcfR)
library(txdbmaker)
library(GenomicFeatures)
library(GenomicRanges)
library(GenomeInfoDb)
library(BiocGenerics)
library(S4Vectors)
library(AnnotationDbi)
library(VariantAnnotation)
library(rTASSEL)

genes_file <- "ricegenes.txt"
subpop = "3k_subpop.txt"
source("scripts/data_summary.R")
source("scripts/candidate_gene.R")
source("scripts/hap_phe2.R")
source("scripts/func_piechart.R")
source("scripts/pca_plot.R")
source("scripts/qc_linux.R")
source("scripts/extract_irisID.R")
source("scripts/association_main.R")
source("scripts/candidate_gene.R")
source("scripts/hap_phe2.R")
source("scripts/func_piechart.R")
source("scripts/annotation.R")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Server start
shinyApp(ui = ui, server = server)

